apply plugin: 'com.android.application'

description = 'OSH Android App'
ext.details = 'OSH app for Android'

repositories {
//  maven {
//    url "https://repo.eclipse.org/content/repositories/paho-releases/"
//  }
}

dependencies {
    api project(':sensorhub-android-lib')

    implementation 'org.eclipse.paho:org.eclipse.paho.client.mqttv3:1.2.5'
    implementation 'org.eclipse.paho:org.eclipse.paho.android.service:1.1.1'
    implementation 'com.google.android.material:material:1.9.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation 'androidx.navigation:navigation-fragment:2.5.3'
    implementation 'androidx.navigation:navigation-ui:2.5.3'
    implementation 'androidx.cardview:cardview:1.0.0'
    implementation 'androidx.coordinatorlayout:coordinatorlayout:1.2.0'
    implementation 'androidx.preference:preference:1.2.0'

    implementation project(path: ':sensorhub-datastore-h2')
    implementation project(path: ':sensorhub-service-consys')
    implementation project(path: ':sensorhub-service-discovery')
    implementation project(':sensorhub-android-ste')
    implementation project(':sensorhub-android-meshtastic')
    implementation project(':sensorhub-android-polar')
    implementation project(':sensorhub-android-wardriving')
    implementation project(':sensorhub-android-controller')
    implementation project(':sensorhub-android-template')
    implementation project(':sensorhub-driver-android')
    implementation 'org.slf4j:slf4j-api:2.0.9'
    implementation 'com.github.tony19:logback-android:3.0.0'

}

allprojects {
    configurations.all {

        exclude group: 'ch.qos.logback', module: 'logback-classic'
        exclude group: 'ch.qos.logback', module: 'logback-core'

        resolutionStrategy {
            force "org.jetbrains.kotlin:kotlin-stdlib:1.8.10"
            force "org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.8.10"
            force "org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.8.10"
        }
    }
}

android {
    namespace 'org.sensorhub.android'
    compileSdkVersion rootProject.compileSdkVersion
    buildToolsVersion rootProject.buildToolsVersion

    defaultConfig {
        minSdkVersion rootProject.minSdkVersion
        targetSdkVersion rootProject.targetSdkVersion
        versionCode 1
        versionName rootProject.version
        applicationId "com.georobotix.android"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    packagingOptions {
        exclude 'META-INF/LICENSE'
        exclude '**/empty'
        exclude 'META-INF/rxjava.properties'
    }


    sourceSets {
        main {
            manifest.srcFile 'AndroidManifest.xml'
            java.srcDirs = ['src']
            res.srcDirs = ['res']
            assets.srcDirs = ['assets']
            resources.srcDirs = ['src/main/resources']
        }
    }

    applicationVariants.all { variant ->
        variant.outputs.all {
            outputFileName = "osh-android-${variant.versionName}-${variant.name}.apk"
        }
    }

    lintOptions {
        abortOnError false
    }
    buildFeatures {
        viewBinding true
    }

    packagingOptions {
        resources {
            excludes += ["META-INF/INDEX.LIST"]
        }
    }

}

