name: Build APK

on:
  push:
    branches: [ master, dev, ci-cd ]
  pull_request:
    branches: [ master, dev ]

env:
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Configure SSH for private submodules
        if: env.SSH_PRIVATE_KEY != ''
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ env.secrets.SSH_PRIVATE_KEY }}

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          packages: ''

      - name: Build APK
        run: |
          chmod +x ./gradlew
          ./gradlew build -x test -x osgi -x lintDebug -x javadoc

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: osh-android-APK
          path: sensorhub-android-app/build/outputs/apk/debug/sensorhub-android-app-debug.apk

      - name: Create GitHub Release
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v2
        with:
          files: app/build/outputs/apk/basic/release/*.apk
          generate_release_notes: true